import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Идёт разработка',
	description: 'Generated by create next app',
}

export default async function DevLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return <>{children}</>
}
