import dynamic from 'next/dynamic'

import { Header } from '@/widgets'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Главная',
	description: 'Generated by create next app',
}
const Footer = dynamic(() => import('@/widgets').then(mod => mod.Footer), {
	loading: () => <div>Загрузка...</div>,
})
export default async function PublicLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<Header />
			{children}
			<Footer />
		</>
	)
}
