import { type Metadata } from 'next'

import { SignInForm } from '@/features/auth/SignIn/ui/SignInForm'

import './../styles.scss'

export const metadata: Metadata = {
	title: 'Авторизация',
	description: 'Generated by create next app',
}
export default function SignIn() {
	return (
		<main>
			<section className="AuthIndex signIn">
				<div className="container">
					<div className="Auth__inner">
						<SignInForm />
					</div>
				</div>
			</section>
		</main>
	)
}
