import type { Metadata } from "next";
import { Roboto, Unbounded } from "next/font/google";
import "./globals.scss";
import { Header } from "@/widgets/Header";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});
const unbounded = Unbounded({
  variable: "--font-unbounded-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${unbounded.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
