import { Roboto, Unbounded } from "next/font/google";

import { Header, Footer } from "@/widgets";

import type { Metadata } from "next";

import "./globals.scss";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});
const unbounded = Unbounded({
  variable: "--font-unbounded-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${unbounded.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
