import { type Metadata } from 'next'

import { SignUpPageContent } from '@/features/auth/SignUp/ui/SignUpPageContent'

import styles from './../../page.module.scss'

export const metadata: Metadata = {
	title: 'Регистрация',
	description: 'Generated by create next app',
}
export default function SignUp() {
	return (
		<main className={styles.index}>
			<section className={styles.signUp}>
				<div className="container">
					<div className={styles.inner}>
						<SignUpPageContent />
					</div>
				</div>
			</section>
		</main>
	)
}
