import { type Metadata } from 'next'

import { SignUpPageContent } from '@/features/auth/SignUp/ui/SignUpPageContent'

import '../styles.scss'

export const metadata: Metadata = {
	title: 'Регистрация',
	description: 'Generated by create next app',
}
export default function SignUp() {
	return (
		<main className="AuthIndex">
			<section className="signUp">
				<div className="container">
					<div className="Auth__inner">
						<SignUpPageContent />
					</div>
				</div>
			</section>
		</main>
	)
}
