import { Header, Footer } from '@/widgets'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Главная',
	description: 'Generated by create next app',
}

export default function PrivateLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<Header />
			{children}
			<Footer />
		</>
	)
}
