name: Desharing CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Получаем всю историю коммитов для pre-commit проверок
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run pre-commit checks
        run: |
          # Устанавливаем husky и запускаем pre-commit проверки
          npm run prepare
          npx husky install
          # Запускаем pre-commit проверки для измененных файлов
          npx lint-staged

      - name: Run full ESLint check
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Run tests with Vitest
        run: npm test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: quality-checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next
